package com.example.demo.utility;

public enum Permission {
    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    USER_MANAGE_ROLES,

    ROLE_READ,
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,

    CATEGORY_READ,
    CATEGORY_CREATE,
    CATEGORY_UPDATE,
    CATEGORY_DELETE,

    TAG_READ,
    TAG_CREATE,
    TAG_UPDATE,
    TAG_DELETE,

    POST_READ,
    POST_READ_OWN_DRAFTS,
    POST_READ_ALL,
    POST_CREATE,
    POST_UPDATE_OWN,
    POST_UPDATE_ANY,
    POST_DELETE_OWN,
    POST_DELETE_ANY,
    POST_SUBMIT_DRAFT,
    POST_APPROVE,
    POST_REJECT,
    POST_PUBLISH,
    POST_UNPUBLISH,

    COMMENT_READ,
    COMMENT_CREATE,
    COMMENT_UPDATE_OWN,
    COMMENT_UPDATE_ANY,
    COMMENT_DELETE_OWN,
    COMMENT_DELETE_ANY,
    COMMENT_MODERATE,

    POST_LIKE,

    CONTENT_SEARCH,

    PROFILE_UPDATE_OWN,
    PROFILE_UPDATE_ANY,

    SYSTEM_CONFIG_READ,
    SYSTEM_CONFIG_UPDATE,
    SYSTEM_MAINTENANCE
}